name: Run Robot Framework Tests

on:
  schedule:
    - cron: '0 18 * * *' # Schedule to run daily at 6 PM Central Time
  push:
    branches:
      - main # Run on push events to the main branch
  pull_request:
    branches:
      - main # Run on pull requests to the main branch
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  run-tests:
    runs-on: ubuntu-latest # Use the latest version of Ubuntu

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2 # Checkout the repository code

    - name: Set up Python
      uses: actions/setup-python@v2 # Set up the Python environment
      with:
        python-version: '3.9' # Specify the Python version to use

    - name: Install pipenv
      run: |
        python -m pip install --upgrade pip # Upgrade pip to the latest version
        pip install pipenv # Install pipenv

    - name: Install dependencies
      run: pipenv install --dev --python 3.9 # Install dependencies from the Pipfile specifying Python 3.9

    - name: Install Chrome
      run: |
        sudo apt-get update # Update the package list
        sudo apt-get install -y wget # Install wget
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb # Download the latest stable version of Google Chrome
        sudo dpkg -i google-chrome-stable_current_amd64.deb # Install the downloaded Chrome package
        sudo apt-get install -f # Fix broken dependencies, if any

    - name: Run Robot Framework tests
      run: pipenv run robot -d output robot-framework/tests/test.robot # Run the Robot Framework tests and output results to the 'output' directory

