name: Run Valkyrie Test Automation Framework Tests

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest # Use the latest version of Ubuntu

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3 # Checkout the repository code

    - name: Set up Python
      uses: actions/setup-python@v3 # Set up the Python environment
      with:
        python-version: '3.9' # Specify the Python version to use

    - name: Install pipenv
      run: |
        python -m pip install --upgrade pip # Upgrade pip to the latest version
        pip install pipenv # Install pipenv
        
    - name: Install dependencies
      run: pipenv install --dev --python 3.9 # Install dependencies from the Pipfile specifying Python 3.9

    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y wget apt-transport-https ca-certificates gnupg
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
